### ISSUE TITLE
Number of filers 

### ISSUE THREAD

**Issue by trungpham2606** [EricAlcaide/SimpleNet-Keras#3]
According to the paper you had cited, I found that the architecture of your implementation did not match with author's architecture. I was unable to find the number 2048 in the paper ? Can you explain for me or show me whether I missed something ? 
Best regard

**Comment by hypnopump** [comment]
Check it here (Caffe logs describing the architecture):  https://github.com/Coderx7/SimpleNet/blob/master/SimpNet_V1/Models/NoDropout/train_test.prototxt I tried to replicate the architecture here described. 

Also check the first version of the paper (PDF): https://arxiv.org/vc/arxiv/papers/1608/1608.06037v1.pdf in Table1 it is said that the first CCCP contains 2048 filters.

I hope this solves the issue.

**Comment by hypnopump** [comment]
Closing the issue
